### ISSUE TITLE
Eula window text color

### ISSUE THREAD

**Issue by cutelittlecow** [cutelittlecow/eqclassic-ui#4]
Text should be black instead of white. Don't believe this is modifiable from within the XML script.

**Comment by iMotoGames** [comment]
Unable to fix due to client constraints. Like the server list, I believe the text colors are sent via packets in the server.

This should be brought up to the GM's when the EQLSUI is completely finished and submitted for use in their patch.

**Comment by iMotoGames** [comment]
For a better description as to why this cannot be fixed by strictly UI means. It seems that the definition for STMLbox doesnt have direct access to TextColor

**Comment by cutelittlecow** [comment]
Managed to figure this out and fix it in a recent commit.
